### ISSUE TITLE
Add support for beforeEach/afterEach

### ISSUE THREAD

**Issue by sjbarag** [hulu/roca#20]
We should include some way to execute code in several setup/teardown phases:

* `beforeEach` (like in [jasmine](https://jasmine.github.io/api/3.5/global.html#beforeEach)): before every test in a suite (and its subsuites)
* `afterEach` (like in [jasmine](https://jasmine.github.io/api/3.5/global.html#afterEach])): after every test in a suite (and its subsuites)

Note that this'll probably require making sure there's a place to put shared state between tests since BrightScript doesn't support closures like JavaScript does.

**Comment by lkipke** [comment]
Going to edit this down to just `beforeEach`/`afterEach`
